version: '3'
services:
  app:
    image: devops-msa
    deploy:
      replicas: 2
  load-balancer:
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf