version: '3'
services:
  app:
    image: devops-microservice
    deploy:
      replicas: 2
  load-balancer:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf