# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-msa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-msa
  template:
    metadata:
      labels:
        app: devops-msa
    spec:
      containers:
      - name: devops-msa
        image: auroyolimar5/devops-msa:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: devops-msa
spec:
  selector:
    app: devops-msa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: devops.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devops-msa
            port:
              number: 80